<?php 
/*
ESTE OPERADOR É UMA ESTRUTURA CONDICIONAL RESUMIDA;
NA MAIORIA DAS VEZES SERÁ UTILIZADO MESMO O IF ELSE;
PORÉM EM SITUAÇÕES SIMPLES PODEMOS UTILIZAR O TERNÁRIO;
EXEMPLO: ECHO 5 > 2 ? "5 É MAIOR QUE 2" : "5 É MENOR QUE 2";   
A  INTERROGAÇÃO VEM DEPOIS DA COMPARAÇÃO;
E O : É UTILIZADO PARA UMA SEGUNDA SITUAÇÃO, CASO A PRIMEIRA SEJA FALSE;

A ? SIGNIFICA O IF E OS : SIGNIFICAM ELSE - EM RESUMO
*/

#NA PRÁTICA

$n1 = 3;
$n2 = 5;

echo $n1 < $n2 ? "<h1> $n1 é menor que $ <br>" :  "$n1 é maior que $n2<br>";

#COM OPERADORES LÓGICOS

echo $n1 > 2 && $n2 < 6 ? "Deu true<br>" : "Deu false <br>"
?>