<?php 
/*
O QUE É UMA EXPRESSÃO?

uma instrução de código que será avaliada e retornará um valor

uma simples impressão de um texto

uma soma ou operação matemática mais complexa também

na programação realizaremos diversas expressões durante o nosso código, para formar nosso software

várias expressões reultam em um software


O QUE É UM OPERADOR

SÃO RECURSOS PARA EFETUAR CÁLCULOS OU COMPARAÇÕES

UM NOVO VALOR É GERADO POR UM CÁLCULO OU UM TRUE/FALSE PODE SER RETORNADO SE VIER UM VALOR BOOLEAN

A ORDEM DE PRECEDÊNCIA DAS OUTRAS LINGUAGENS É A MESMA EM PHP 

O PHP CONVERTE UM NÚMERO INT PARA FLOAT SEM PROBLEMAS ASSIM:
EX 5/2 = 2.5
EM OUTRAS LINGUAGENS MAIS ANTIGAS ISSO TALVEZ NÃO FOSSE POSSÍVEL

O . SERVE PARA CONCATENAR

ENTÃO SE EU FIZER 5 . 5 ISSO GERAÁ UMA STRING COM O RESULTADO '55'

ISSO SE CHAMA AUTO CAST

ISSO PODE SER PERIGOSO CASO EU NÃO QUEIRA QUE OS VALORES VIREM FLOAT OU STR, ENTÃO DEVO TER CUIDADO QUANTO A ISSO



*/
?>