<?php 

echo "<h1>Hello, world! </h1>";
/*
 O QUE É LOCALHOST?
  *É UMA FORMA DE ACESSAR O SERVIDOR
  *EQUIVALE AO IP 127.0.0.1, OU SEJA, O NOSSO PC(COMO SE FOSSE UM NOME BONITO PARA O IP DA NOSSA MÁQUINA)
  *CADA SITE TEM O SEU DNS(DOMAIN NAME SERVER) QUE SERVEM PARA "MASCARAR" OS IPS, NO CASO DO LOCAL HOST DIGITAMOS ELE PARA "NASCARAR" O 127.0.0.1
 */

?>