<?php 

/* O QUE SÃO FUNÇÕES?

    -SÃO BLOCOS DE CÓDIGO QUE POSSUEM NOMES;
    
    -REALIZAM UMA AÇÃO E PODEM SER REAPROVEITADAS(CHAMADAS NOVAMENTE) AO LONGO DO PROGRAMA;
    
    -PODEMOS PASSAR PARÂMETROS PARA FUNÇÃO, QUE MOLDAM SUA EXECUÇÃO;
    
    -A CRIAÇÃO DE FUNÇÕES REDUZ A DUPLICIDADE DE CÓDIGO;
    
    -E TAMBÉM MELHORA A MANUTENÇÃO DO MESMO;
    
    -O PHP POSSUI DIVERSAS FUNÇÕES PRONTAS, QUE PODEMOS UTILIZAR;

    ESTRUTURA DE UMA FUNÇÃO ↓↓
    function teste(){
       
    }
*/

?>