<?php 
/*
    - LOOP INFINITO É QUANDO VOCÊ NÃO COLOCA UM LIMITE NO MESMO, OU QUANDO NÃO SE COLOCA O INCREMENTO OU DECREMENTO PARA CHEGAR ATÉ A CONDIÇÃO;
    -EX X >10 E A VAR DE REFERÊNCIA TEM UM DECREMENTO, NÃO UM INCREMENTO;
    - ISSO VAI FAZER O SOFTWARE TRAVAR, E PODE SER UM GRANDE PROBLEMA CASO OS USUÁRIOS ESTIVEREM ACESSANDO O MESMO;

    for ($i=0; $i < 10; $i--) { 
        echo "Teste <br>";
    }
    ESTE É UM LOOP INFINITO ↑↑

*/


?>